Словари +
Функции +
lambda - функции
Pandas работа с столбцами +--
Функции + Pandas +
Методы Pandas -

In [3]:
import pandas as pd
import numpy as np

In [2]:
def count_all_rows(dct_df: dict[str, pd.DataFrame]):
    couter = 0

    for key in dct_df:
        print(f"{key} - {dct_df[key].shape[0]} rows")
        couter += dct_df[key].shape[0]

    return couter

In [3]:
def axe_analitic(column):
    size = column.shape[0]
    null = column.isnull()

    return f"{round(null.sum() * 100 / size, 2)}%"

In [5]:
df_dict = {'mpg': pd.read_csv("mpg.csv"),
           'tips': pd.read_csv("tips.csv"),
           'bank': pd.read_csv("bank-full.csv"),
           'titanik': pd.read_csv("titanic_for_mac_users.csv")}

In [6]:
count_all_rows(df_dict)

mpg - 398 rows
tips - 244 rows
bank - 41188 rows
titanik - 891 rows


42721

In [7]:
df_dict['tips'][['sex', 'tip']]

sex   tip
0    Female  1.01
1      Male  1.66
2      Male  3.50
3      Male  3.31
4    Female  3.61
..      ...   ...
239    Male  5.92
240  Female  2.00
241    Male  2.00
242    Male  1.75
243  Female  3.00

[244 rows x 2 columns]

In [8]:
df_dict['mpg'][['weight', 'name']]

weight                       name
0      3504  chevrolet chevelle malibu
1      3693          buick skylark 320
2      3436         plymouth satellite
3      3433              amc rebel sst
4      3449                ford torino
..      ...                        ...
393    2790            ford mustang gl
394    2130                  vw pickup
395    2295              dodge rampage
396    2625                ford ranger
397    2720                 chevy s-10

[398 rows x 2 columns]

In [9]:
# def check_df_col(df_list: dict, table_columns: dict):
#     
#     for k, v in table_columns.items():
#         df_list

In [10]:
df_dict['tips']['total_bill']

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...  
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [11]:
df_dict['bank'].columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'subscribed'],
      dtype='object')

In [12]:
table_columns = {'titanik': ['class', 'age'], 'mpg': ['name', 'origin', 'mpg']}

In [13]:
def check_columns(df_dict, table_columns):
    for k, v in table_columns.items():
        print(f"Таблица - {k}")

        for col in v:
            Na_per = axe_analitic(df_dict[k][col])
            print(f"Столбец - {col} - {Na_per} пропущенных")
        
        print('-' * 40)

In [14]:
check_columns(df_dict=df_dict, table_columns=table_columns)

Таблица - titanik
Столбец - class - 0.0% пропущенных
Столбец - age - 19.87% пропущенных
----------------------------------------
Таблица - mpg
Столбец - name - 0.0% пропущенных
Столбец - origin - 0.0% пропущенных
Столбец - mpg - 0.0% пропущенных
----------------------------------------


In [15]:
def check_columns2(df_dict, **kwargs):
    print(kwargs)
    for k, v in kwargs.items():
        print(f"Таблица - {k}")

        for col in v:
            Na_per = axe_analitic(df_dict[k][col])
            print(f"Столбец - {col} - {Na_per} пропущенных")
        
        print('-' * 40)

In [16]:
check_columns2(df_dict=df_dict, titanik=['class', 'age'], mpg=['name', 'origin', 'mpg'])

{'titanik': ['class', 'age'], 'mpg': ['name', 'origin', 'mpg']}
Таблица - titanik
Столбец - class - 0.0% пропущенных
Столбец - age - 19.87% пропущенных
----------------------------------------
Таблица - mpg
Столбец - name - 0.0% пропущенных
Столбец - origin - 0.0% пропущенных
Столбец - mpg - 0.0% пропущенных
----------------------------------------


In [ ]:
# Позиционные параметры
# Именованные параметры

In [ ]:
# Функция только с именнованными/позиционные одиночные параметрами
def func1(a: int, b: str, c: bool):
    print(f"a - {a}, b - {b}, c - {c}")

In [87]:
func1(a=4, c=True, b='a')

a - 4, b - a, c - True


In [108]:
# Функция с множественными именованными и позиционными параметрами

def many_func(a, b, *args, c, d, **kwargs):
    print(f'a - {a}')
    print(f'b - {b}')
    print(f'*args - {args}')
    print(args)
    print(f'a - {c}')
    print(f'b - {d}')
    print(f'**kwargs - {kwargs}')

In [109]:
many_func(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, c=11, d=12, asd=46, sdfsdfsdf=1)

a - 1
b - 2
*args - (3, 4, 5, 6, 7, 8, 9, 10)
(3, 4, 5, 6, 7, 8, 9, 10)
a - 11
b - 12
**kwargs - {'asd': 46, 'sdfsdfsdf': 1}


In [120]:
dict(titanik=['class', 'age'], mpg=['name', 'origin', 'mpg'])

{'titanik': ['class', 'age'], 'mpg': ['name', 'origin', 'mpg']}

In [ ]:
dict()

## lambda-фунцкия это тоже самое что и обычная функция

In [121]:
def sample_func(var):
    return var

In [122]:
lambda_func = lambda var: var

In [130]:
sample_func(var=5)

5

In [124]:
lambda_func(var=5)

5

In [ ]:
list(map(lambda var: var[1] + 1, [('a', 1), ('b', 2), ('c', 3)]))

[2, 3, 4]

In [143]:
num: int = 'a'

In [144]:
num

'a'

In [145]:
df_dict['mpg']['name'].iloc[1]

'buick skylark 320'

In [5]:
ar_range = np.arange(0, 10, 2)
print(ar_range)

[0 2 4 6 8]


In [13]:
ar_full = np.full((3, 3), 0.5)
print(ar_full)

[[0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]]
