In [ ]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3])
arr + 1

array([2, 3, 4])

In [ ]:
arr_one = np.ones((5, 2))
arr_one

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
np.full((3, 3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [17]:
np.random.seed(42)
arr1= np.random.randint(1, 10, size=(5, 5))
arr1


array([[7, 4, 8, 5, 7],
       [3, 7, 8, 5, 4],
       [8, 8, 3, 6, 5],
       [2, 8, 6, 2, 5],
       [1, 6, 9, 1, 3]], dtype=int32)

In [18]:
arr1[:2, :2]

array([[7, 4],
       [3, 7]], dtype=int32)

In [19]:
arr1[1:, 1:3]

array([[7, 8],
       [8, 3],
       [8, 6],
       [6, 9]], dtype=int32)

In [47]:
arr1[1::2,  1::2]

array([[7, 5],
       [8, 2]], dtype=int32)

In [48]:
arr1 = np.arange(1, 10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.select([arr1 < 4, arr1 > 6], ['меньше', 'больше'], default=np.nan)

TypeError: Choicelist and default value do not have a common dtype: The DType <class 'numpy.dtypes._PyFloatDType'> could not be promoted by <class 'numpy.dtypes.StrDType'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes._PyFloatDType'>)