In [1]:
import numpy as np


np.random.seed(42)
arr = np.random.randint(10, 101, size=(6, 6))
print("Исходный массив:\n", arr)

filtered = arr[(arr >= 30) & (arr <= 70)]
print("\nОтфильтрованный массив:\n", filtered)

count = filtered.size
total = filtered.sum()
mean = round(filtered.mean())



Исходный массив:
 [[ 61  24  81  70  30  92]
 [ 96  84  84  97  33  12]
 [ 31  62  11  97  39  47]
 [ 11  73  69  30  42  85]
 [ 67  31  98  58 100  68]
 [ 51  69  89  24  71  71]]

Отфильтрованный массив:
 [61 70 30 33 31 62 39 47 69 30 42 67 31 58 68 51 69]


In [2]:
print(f"\nКоличество: {count}")
print(f"Сумма: {total}")
print(f"Среднее арифметическое: {mean}")


Количество: 17
Сумма: 858
Среднее арифметическое: 50


In [3]:
import numpy as np

def check_num(arr):
    result = []
    for num in arr:
        digits = [int(d) for d in num]
        first_sum = digits[0] + digits[1]
        last_sum = digits[2] + digits[3]
        result.append(first_sum == last_sum)
    return result

# Пример 1
arr1 = np.array(['1234', '5610', '3425', '9081', '7733'])
mask1 = check_num(arr1)
output1 = np.where(mask1, 'good', 'bad')
print("Пример 1:")
print(output1)

# Пример 2
arr2 = np.array(['1122', '4536', '8909', '2314', '7667', '7214', '3098'])
mask2 = check_num(arr2)
output2 = np.where(mask2, 'good', 'bad')
print("\nПример 2:")
print(output2)


Пример 1:
['bad' 'bad' 'good' 'good' 'bad']

Пример 2:
['bad' 'good' 'bad' 'good' 'good' 'bad' 'bad']


In [ ]:
import numpy as np

arr_salary = np.array([
    2051, 1784, 1670, 2002, 2239, 1870, 1713, 1789, 2170, 1996,
    1425, 1612, 2387, 1599, 2692, 2703, 2696, 1560, 2038, 1753,
    2384, 2462, 2853, 2437, 2005, 1817, 2325, 1389, 2268, 1543
])

arr_currency = np.array([
    'USD', 'EUR', 'USD', 'EUR', 'USD', 'USD', 'TJK', 'TJK', 'USD', 'EUR',
    'USD', 'TJK', 'TJK', 'TJK', 'EUR', 'USD', 'TJK', 'USD', 'EUR', 'EUR',
    'EUR', 'TJK', 'EUR', 'USD', 'TJK', 'USD', 'USD', 'EUR', 'EUR', 'EUR'
])


exchange_rates = {
    'USD': 9.12,
    'EUR': 10.17,
    'TJK': 1.00
}


get_rate = np.vectorize(lambda cur: exchange_rates[cur])
rates = get_rate(arr_currency)

converted_salary = (arr_salary * rates).astype(int)

print("Изначальные суммы:", arr_salary)
print("Валюта:", arr_currency)
print("Курс для каждой транзакции:", rates)
print("Суммы в TJK:", converted_salary)


Изначальные суммы: [2051 1784 1670 2002 2239 1870 1713 1789 2170 1996 1425 1612 2387 1599
 2692 2703 2696 1560 2038 1753 2384 2462 2853 2437 2005 1817 2325 1389
 2268 1543]
Валюта: ['USD' 'EUR' 'USD' 'EUR' 'USD' 'USD' 'TJK' 'TJK' 'USD' 'EUR' 'USD' 'TJK'
 'TJK' 'TJK' 'EUR' 'USD' 'TJK' 'USD' 'EUR' 'EUR' 'EUR' 'TJK' 'EUR' 'USD'
 'TJK' 'USD' 'USD' 'EUR' 'EUR' 'EUR']
Курс для каждой транзакции: [ 9.12 10.17  9.12 10.17  9.12  9.12  1.    1.    9.12 10.17  9.12  1.
  1.    1.   10.17  9.12  1.    9.12 10.17 10.17 10.17  1.   10.17  9.12
  1.    9.12  9.12 10.17 10.17 10.17]
Суммы в TJK: [18705 18143 15230 20360 20419 17054  1713  1789 19790 20299 12995  1612
  2387  1599 27377 24651  2696 14227 20726 17828 24245  2462 29015 22225
  2005 16571 21204 14126 23065 15692]
